### ISSUE TITLE
Can't build Freescale FEC Ethernet Driver as Module because of missing exports in net/core/tso.c

### ISSUE THREAD

**Issue by fira** [SolidRun/linux-fslc#20]
Ran into this exact problem before some head-against-wall action, and eventually running into this : 

https://ko.osdn.jp/projects/uclinux-h8/scm/git/linux/commits/484611e53047b55163822bfe60424a55a31775b3

If you're wondering why i'm building FEC as Module, it's because I need to use RTnet/Xenomai and be able to switchover to the Realtime driver.

**Comment by linux4kix** [comment]
Thank you for the report.  I will patch this.

**Comment by linux4kix** [comment]
The upstream fix for this has been backported into the current tree.
