### ISSUE TITLE
Bluetooth doesn't work for HummingBoard2 Solo/Dual Lite

### ISSUE THREAD

**Issue by AAndranik** [SolidRun/linux-fslc#36]
Gave this kind of error at bootlog:
- [warn] Not correct BT chip ... (warning).

I think something is changed in connection with microSOM compared with previous hummingboard edge, so there is need to do some changes in hummingboard2's device tree.

**Comment by warped-rudi** [comment]
How do you detect the bluetooth chip?
ISTR, that - depending on the kernel or board - the BCM43xx will either appear under /sys/class/mmc_host/mmc1/... or /sys/class/mmc_host/mmc0/...

**Comment by AAndranik** [comment]
There are lot of files/folders in /sys/class/mmc_host/mmc0 and mmc1:
      device  mmc0:aaaa  power  subsystem  uevent
      device  mmc1:0001  power  subsystem  uevent
also there is mmc2 folder.
I can't find BCM43.. there

**Comment by warped-rudi** [comment]
What does:

```
cat "/sys/class/mmc_host/mmc1/mmc1:0001/mmc1:0001:1/device"
```

say? It should show the ID of your bluetooth chip. I.e. "0x4330" for BCM4330 or "0x4329" for BCM4329 found on older uSOMs. Your OS should use this information to decide which firmware to load.

**Comment by AAndranik** [comment]
It returns "0x4330".
There are "bcm4330.hcd", "brcmfmac4330-sdio.bin" and "brcmfmac4330-sdio.txt" files in "/lib/firmware/brcm/" directory but in bootlog I always receive the message "[warn] Not correct BT chip ... (warning)" so the OS couldn't load correct firmware for "bcm4330".

**Comment by AAndranik** [comment]
I found that bluetooth works on Debian Jessie (8.0) but doesn't work on Debian Wheezy (7.0).

**Comment by jnettlet** [comment]
Please test this against our latest 4.9 kernel. https://github.com/SolidRun/linux-fslc Currently this still requires the userspace firmware loader for the broadcom bluetooth support, however I have backported the serdev framework support into the kernel and will work on wiring that up for our older SOMs in the near future.
