### ISSUE TITLE
pci lockup

### ISSUE THREAD

**Issue by warped-rudi** [SolidRun/linux-fslc#38]
I'm seeing a  freeze here when trying to use an Intel Centrino Wireless N-135 card. Famous last words on the console are:

```
cfg80211: Calling CRDA to update world regulatory domain
Intel(R) Wireless WiFi driver for Linux, in-tree:
Copyright(c) 2003- 2014 Intel Corporation
PCI: enabling device 0000:01:00.0 (0000 -> 0002)
```

After the last message, the system is unresponsive. There are no logs. Hardware is Hummingboard i2ex. I'm quite positive that I was able to boot the system with that card inserted a while back.

**Comment by warped-rudi** [comment]
Arrgh! Looks like this was caused by a contact problem (uSOM incorrectly seated on the carrier board). Now it works. Closing...

**Comment by rabeeh** [comment]
Great. Thx.
