### ISSUE TITLE
Cannot get streaming to work with TC358743 and B100

### ISSUE THREAD

**Issue by wuestenarchitekten** [SolidRun/linux-fslc#41]
Hello,

i compiled the Kernel and installed it on a Huumingboard but I can't get the TC358743 driver for the B100 from Auvidea (http://www.auvidea.eu/index.php/theme-styles/2014-12-30-22-32-06/b100-hdmi-to-csi-2-bridge) working.
In a different discussion I've read that the i2c adapter id of the b100 is 1 while often the default is something else. I tried changing the i2c_device_id in tc358743_h2c.c without this solving my issues.

Thanks,
Markus

**Comment by jnettlet** [comment]
Please test this against our latest 4.9 kernel https://github.com/SolidRun/linux-fslc  If the problem still exists open a new bug against it.  Thanks
