### ISSUE TITLE
UART3 mikrobus ttymxc2 doesn't work on HBE

### ISSUE THREAD

**Issue by ljburtz** [SolidRun/linux-fslc#44]
HBE v1.2
SoM i1 solo v1.3 (same results with v1.5 also)
sr-imx6-debian-jessie-cli-20160226.img 

there is a simple patch in a thread on the forum :
http://forum.solid-run.com/linux-on-cubox-i-and-hummingboard-f8/uart3-ttymxc2-mikrobus-nothing-happens-and-uart2-t-t3100.html> 

I'm wondering why TX and RX were swapped and why it had 0x40013000 instead of 0x1b0b1
Note also: the fix includes disabling both the TX and RX UART DMA drivers

**Comment by ljburtz** [comment]
update on the DMA:

test | imx6qdl-hummingboard2.dtsi | result
---| ---| ---
both DMA disabled |  dma-names = "", "";	| works both ways
RX DMA enabled / TX DMA disabled |	dma-names = "rx", ""; |	works both ways **
RX DMA disabled / TX DMA enabled |	dma-names = "", "tx";	| works both ways
both DMA enabled | dma-names = "rx", "tx";	| sending from the HBE works / receiving doesn’t work
both DMA enabled but swapped	| dma-names = "tx", "rx";	| sending from the HBE works / receiving doesn’t work

(all above tests include the modified pinctrl lines as described in the patch on the forum )

** but when starting loopback test, dmesg shows :
[   25.284882] imx-uart 21ec000.serial: cannot get the TX DMA channel!

**Comment by jnettlet** [comment]
This was an issue that has been fixed in newer board spins.  It has been fixed in newer kernel releases but there is no way to detect the board revision programmatically.  If you are still having problems please open a new bug based on the latest device-tree changes and we will look into it.

**Comment by emilppeter** [comment]
Hi,
I am using SolidRun HummingBoard Edge (i.MX6 Quad 2GB Ram). I am also facing the same issue with UART3 pins on the mikrobus and I am unable to find UART2 in the list of serial ports available when I execute the command "dmesg | grep tty". I am using Debian 9.9 on my board and the firmware is 4.9.150.
