### ISSUE TITLE
uSom v1.5 DTS

### ISSUE THREAD

**Issue by joshwelschmeyer** [SolidRun/linux-fslc#46]
Any plans to push the latest Cubox/Hummingboard Device Tree files up to mainline linux?
i.e. imx6dl-cubox-i-som-v15.dts etc.

**Comment by jnettlet** [comment]
These are now pushed to mainline.  We have also adapted our mainline tracking u-boot to properly be able to use the new configurations with specific -emmc variants.  https://github.com/SolidRun/u-boot/tree/master-mx6
