### ISSUE TITLE
4.9: Hummingboard upper USB port not working

### ISSUE THREAD

**Issue by warped-rudi** [SolidRun/linux-fslc#52]
On my Hummingboard Pro the upper USB port does not work with the new kernel. _lsusb_ shows only one root hub where there should be two.

**Comment by linux4kix** [comment]
Yep the mainline patches have the USBOTG_ID pin wrong.  Will fix.

**Comment by jnettlet** [comment]
Fixed in commit 60ce003ad1b55da13781eafb7f144f7d60a0dfce
