### ISSUE TITLE
Bluetooth init errors

### ISSUE THREAD

**Issue by warped-rudi** [SolidRun/linux-fslc#61]
I see (failing) attempts to initialize Bluetooth on SoMs that don't have BT/WIFI at all.

Also: Is there a way to switch back to the old mechanism of firmware loading from user space?
I have not tested this yet, but in the past there were a lot of problems when trying to run BT and WIFI simultaneously. Therefore we had disabled BT-firmware loading (which instantiates the HCI device) by default and the user could enable it when needed by unmasking a systemd unit.

**Comment by jnettlet** [comment]
We currently do not create specific device-tree files for devices that don't have BT/WIFI installed.  These can be disabled by changing the device-tree status for either sub-node you don't want probed.

I recommend using the rfkill subsystem to disable either radio or both if you want. I have updated the device-tree to better match the various power-saving / radio controls of the wifi chips so this should be sufficient and easier to manage than systemd services.
