### ISSUE TITLE
Branch imx_4.9.y is missung hummingboard2 dts files

### ISSUE THREAD

**Issue by warped-rudi** [SolidRun/linux-fslc#64]
Is that intended?

**Comment by jnettlet** [comment]
imx_4.9.y was posted as a temporary placeholder for the iMX8M boards and has no support for our iMX6 platforms, other than 4.9 mainline patches.  Ultimately we will merge MX6 and MX8 branches, but that is not possible yet as we are waiting for vivante binaries that match the platforms.

additionally, this repository is going to be EOL'd as we are consolidating all our development into a single kernel repository.
